---
- hosts: proxmox_server
  gather_facts: False
  vars:
    id_list:
        - "{{ k8s_master_id }}"
        - "{{ k8s_node1_id }}"
        - "{{ k8s_node2_id }}"
        - "{{ k8s_node3_id }}" 
        - "{{ k8s_node4_id }}" 
        - "{{ k8s_node5_id }}" 
    name_list:
        - "{{ k8s_master_hn }}"
        - "{{ k8s_node1_hn }}"
        - "{{ k8s_node2_hn }}"
        - "{{ k8s_node3_hn }}"
        - "{{ k8s_node4_hn }}"
        - "{{ k8s_node5_hn }}"
  tasks: 
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml
            
      - name: Stopping the VMs.
        shell: qm stop {{ item }}
        become: true
        with_items: "{{ id_list }}"
        ignore_errors: yes

      - name: Destroying the VMs.
        shell: qm destroy {{ item }}
        become: true
        with_items: "{{ id_list }}"
        ignore_errors: yes

      - name: Deleting the Resource Pool.
        shell: pvesh delete /pools/{{ k8s_resource_pool }}
        become: true
        ignore_errors: yes

#      - name: Deleting the Debian qcow2 image.
#        file:
#            path: "/tmp/image.qcow2"
#            state: absent
#        ignore_errors: yes

      - name: Deleting the ~/.kube directory.
        local_action:
            module: file
            path: ~/.kube
            state: absent
        ignore_errors: yes

      - name: Cleaning up ssh known hosts
        local_action:
          module: lineinfile
          path: ~/.ssh/known_hosts
          state: absent
          regexp: "^kmaster0"

      - name: Cleaning up ssh known hosts 2
        local_action:
          module: lineinfile
          path: ~/.ssh/known_hosts
          state: absent
          regexp: '^knode1'

      - name: Cleaning up ssh known hosts 3
        local_action:
          module: lineinfile
          path: ~/.ssh/known_hosts
          state: absent
          regexp: '^knode2'

      - name: Cleaning up ssh known hosts 4
        local_action:
          module: lineinfile
          path: ~/.ssh/known_hosts
          state: absent
          regexp: '^knode3'


          

