---
- hosts: proxmox_server
  gather_facts: False
  serial: 1
  vars:
    id_list:
        - "{{ k8s_master_id }}"
        - "{{ k8s_node1_id }}"
        - "{{ k8s_node2_id }}"
        - "{{ k8s_node3_id }}"      
        - "{{ k8s_node4_id }}"      
        - "{{ k8s_node5_id }}"      
    id_stg_list:
        - { id: "{{ k8s_master_id }}", stg: "{{ k8s_master_stg }}" }
        - { id: "{{ k8s_node1_id }}", stg: "{{ k8s_node1_stg }}" }
        - { id: "{{ k8s_node2_id }}", stg: "{{ k8s_node2_stg }}" }
        - { id: "{{ k8s_node3_id }}", stg: "{{ k8s_node3_stg }}" }      
        - { id: "{{ k8s_node4_id }}", stg: "{{ k8s_node4_stg }}" }      
        - { id: "{{ k8s_node5_id }}", stg: "{{ k8s_node5_stg }}" }      
  tasks:
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml

      - name: Creating a resource pool.
        shell: pvesh create /pools -poolid "{{ k8s_resource_pool }}" --Comment "Kubernetes Cluster"
        become: true
        ignore_errors: yes

      - name: Downloading the qcow2 image.
        get_url:
            url: "{{ qcow2_image }}"
            dest: "{{ qcow2_download_location }}image.qcow2"

      - name: Creating the VMs.
        shell: >
            qm create {{ item.id }}
            --pool {{ k8s_resource_pool }}
            --ostype "l26"
            --name {{ item.hn }}
            --description "Kubernetes VM"
            --agent 1
            --cores {{ item.cpu }}
            --memory {{ item.mem }} 
            --cipassword "Sm0lk0wski"
            --net0 "virtio,bridge={{ item.bridge }},macaddr={{ item.mac }}"
            --nameserver {{ item.ns }}
            --searchdomain {{ item.sd }}
            --sshkeys {{ k8s_ssh_key }}
        become: true
        with_items: 
            - { id: "{{ k8s_master_id }}", hn: "{{ k8s_master_hn }}", cpu: "{{ k8s_master_cpu }}", mem: "{{ k8s_master_mem }}", bridge: "{{ k8s_master_bridge }}", gw: "{{ k8s_master_gw }}", ip: "{{ k8s_master_ip }}", sn: "{{ k8s_master_sn }}", ns: "{{ k8s_master_ns }}", sd: "{{ k8s_master_sd }}", mac:  "{{ k8s_master_mac }}"  }
            - { id: "{{ k8s_node1_id }}", hn: "{{ k8s_node1_hn }}", cpu: "{{ k8s_node1_cpu }}", mem: "{{ k8s_node1_mem }}", bridge: "{{ k8s_node1_bridge }}", gw: "{{ k8s_node1_gw }}", ip: "{{ k8s_node1_ip }}", sn: "{{ k8s_node1_sn }}", ns: "{{ k8s_node1_ns }}", sd: "{{ k8s_node1_sd }}", mac:  "{{ k8s_node1_mac }}"  }
            - { id: "{{ k8s_node2_id }}", hn: "{{ k8s_node2_hn }}", cpu: "{{ k8s_node2_cpu }}", mem: "{{ k8s_node2_mem }}", bridge: "{{ k8s_node2_bridge }}", gw: "{{ k8s_node2_gw }}", ip: "{{ k8s_node2_ip }}", sn: "{{ k8s_node2_sn }}", ns: "{{ k8s_node2_ns }}", sd: "{{ k8s_node2_sd }}", mac:  "{{ k8s_node2_mac }}" }
            - { id: "{{ k8s_node3_id }}", hn: "{{ k8s_node3_hn }}", cpu: "{{ k8s_node3_cpu }}", mem: "{{ k8s_node3_mem }}", bridge: "{{ k8s_node3_bridge }}", gw: "{{ k8s_node3_gw }}", ip: "{{ k8s_node3_ip }}", sn: "{{ k8s_node3_sn }}", ns: "{{ k8s_node3_ns }}", sd: "{{ k8s_node3_sd }}", mac:  "{{ k8s_node3_mac }}" }
            - { id: "{{ k8s_node4_id }}", hn: "{{ k8s_node4_hn }}", cpu: "{{ k8s_node4_cpu }}", mem: "{{ k8s_node4_mem }}", bridge: "{{ k8s_node4_bridge }}", gw: "{{ k8s_node4_gw }}", ip: "{{ k8s_node4_ip }}", sn: "{{ k8s_node4_sn }}", ns: "{{ k8s_node4_ns }}", sd: "{{ k8s_node4_sd }}", mac:  "{{ k8s_node4_mac }}" }
            - { id: "{{ k8s_node5_id }}", hn: "{{ k8s_node5_hn }}", cpu: "{{ k8s_node5_cpu }}", mem: "{{ k8s_node5_mem }}", bridge: "{{ k8s_node5_bridge }}", gw: "{{ k8s_node5_gw }}", ip: "{{ k8s_node5_ip }}", sn: "{{ k8s_node5_sn }}", ns: "{{ k8s_node5_ns }}", sd: "{{ k8s_node5_sd }}", mac:  "{{ k8s_node5_mac }}" }

      - name: Setting the VLAN Tags for the VMs. 
        shell: >
            qm set {{ item.id }}
            --net0 "virtio,bridge={{ item.bridge }},tag={{ item.vlan }}"
        become: true
        with_items:
            - { id: "{{ k8s_master_id }}", bridge: "{{ k8s_master_bridge }}", vlan: "{{ k8s_master_vlan }}" }
            - { id: "{{ k8s_node1_id }}", bridge: "{{ k8s_node1_bridge }}", vlan: "{{ k8s_node1_vlan }}" }
            - { id: "{{ k8s_node2_id }}", bridge: "{{ k8s_node2_bridge }}", vlan: "{{ k8s_node2_vlan }}" }
            - { id: "{{ k8s_node3_id }}", bridge: "{{ k8s_node3_bridge }}", vlan: "{{ k8s_node3_vlan }}" }
            - { id: "{{ k8s_node4_id }}", bridge: "{{ k8s_node4_bridge }}", vlan: "{{ k8s_node4_vlan }}" }
            - { id: "{{ k8s_node5_id }}", bridge: "{{ k8s_node5_bridge }}", vlan: "{{ k8s_node5_vlan }}" }
        when: 
            - k8s_master_vlan is defined 
            - k8s_master_vlan|length != 0
            - k8s_node1_vlan is defined 
            - k8s_node1_vlan|length != 0
            - k8s_node2_vlan is defined 
            - k8s_node2_vlan|length != 0
            - k8s_node3_vlan is defined
            - k8s_node3_vlan|length != 0
            - k8s_node4_vlan is defined
            - k8s_node4_vlan|length != 0
            - k8s_node5_vlan is defined
            - k8s_node5_vlan|length != 0

      - name: Importing the qcow2 image as a disk.
        shell: qm importdisk {{ item.id }} {{ qcow2_download_location }}image.qcow2 {{ item.stg }}
        become: true
        with_items: "{{ id_stg_list }}"

      - name: Configuring the VM Hardware. 
        shell: qm set {{ item.id }} 
               --scsihw virtio-scsi-pci 
               --scsi0 {{ item.stg }}:vm-{{ item.id }}-disk-0
               --ide2 {{ item.stg }}:cloudinit
               --serial0 /dev/tty0
               --boot c --bootdisk scsi0
        become: true
        with_items: "{{ id_stg_list }}"

      - name: Resizing the disk. 
        shell: qm resize {{ item.id }} scsi0 {{ item.size }}
        become: true
        with_items: 
            - { id: "{{ k8s_master_id }}", size: "{{ k8s_master_size }}" }
            - { id: "{{ k8s_node1_id }}", size: "{{ k8s_node1_size }}" }
            - { id: "{{ k8s_node2_id }}", size: "{{ k8s_node2_size }}" }
            - { id: "{{ k8s_node3_id }}", size: "{{ k8s_node3_size }}" }
            - { id: "{{ k8s_node4_id }}", size: "{{ k8s_node4_size }}" }
            - { id: "{{ k8s_node5_id }}", size: "{{ k8s_node5_size }}" }

      - name: Starting the VMs.
        shell: qm start {{ item }}
        become: true
        with_items: "{{ id_list }}"

      - name: Waiting for the VMs to become available.
        wait_for:
            host: "{{ item }}"
            port: 22
            msg: "VMs did not become available after 5 minutes. Network error?"
        with_items: 
            - "{{ k8s_master_hn }}"
            - "{{ k8s_node1_hn }}"
            - "{{ k8s_node2_hn }}"
            - "{{ k8s_node3_hn }}"
            - "{{ k8s_node4_hn }}"
            - "{{ k8s_node5_hn }}"

      - name: Waiting 10 minutes for for Debian to finish booting.
        pause:
            seconds: 600

- hosts: k8s_nodes
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml

      - name: Rebooting the OS, this seems to stablize things 
        become: true
        reboot:
