---
- hosts: k8s_master:k8s_nodes
  gather_facts: False
  vars:
     # created with:
     # python -c 'import crypt; print crypt.crypt("Sm0lk0wski", "$1$SomeSalt$")'
     password: $1$SomeSalt$2u5YyO2WP9NglaUUj8enu.

  tasks:
    - name: Including the variables.
      include_vars:
         file: ../../vars.yml

    - name: Set the password for debian
      become: yes
      user:
        name: debian
        password: "$6$mysecretsalt$1bQSByKowc.ccz/rAEPKcfITHZ5DivENBnoR52kPVP0Ugs81VQZu8REBx55IzB4.GNg1AS0U7IMR0L5JDo2/31"
        update_password: always

